#!/usr/bin/env python3
"""Generate shared identifier ranges from Godot 4.6's Unicode 16 char_range.inc.

Usage: generate_unicode_identifiers.py CHAR_RANGE_INC GRAMMAR_JS
The generated header and patched grammar are checked in; normal builds need no
Unicode downloads or generator. Obtain input from the pinned 4.6-stable source.
"""
import json
import pathlib
import re
import sys

source = pathlib.Path(sys.argv[1]).read_text()
root = pathlib.Path(__file__).resolve().parent.parent
arrays = []
patterns = []
for name in ('xid_start', 'xid_continue'):
    match = re.search(r'constexpr inline CharRange ' + name + r'\[\] = \{.*?\n\};', source, re.S)
    if not match:
        raise SystemExit('Missing ' + name)
    arrays.append(match.group())
    ranges = re.findall(r'\{\s*(0x[0-9A-Fa-f]+),\s*(0x[0-9A-Fa-f]+)\s*\}', match.group())
    def escape(value):
        return r'\u{' + format(int(value, 16), 'X') + '}'
    patterns.append('[_' + ''.join(escape(a) + ('-' + escape(b) if a != b else '') for a, b in ranges) + ']')
license_text = source[:source.index('// This file was generated')]
header = license_text + '// Generated by tools/generate_unicode_identifiers.py from Godot 4.6-stable.\n// Unicode 16.0.0 XID ranges; shared with the patched grammar.\n#pragma once\nnamespace gdscript_lsp::unicode {\nstruct CharRange { char32_t start; char32_t end; };\n' + '\n'.join(arrays) + '\n}\n'
(root / 'src/core/unicode_identifiers.inc').write_text(header)
grammar = pathlib.Path(sys.argv[2])
text = grammar.read_text()
text, count = re.subn(r'    _identifier:.*?\n', lambda _: '    _identifier: ($) => new RegExp(' + json.dumps(patterns[0] + patterns[1] + '*') + ', "u"),\n', text, count=1)
if count != 1:
    raise SystemExit('Missing identifier rule')
grammar.write_text(text)
